
convert: convert.c stb_image.h
	gcc convert.c -lm -o convert

stb_image.h:
	$(error You need to download stb_image.h and place it into this folder. \
		Go to https://github.com/nothings/stb/blob/master/stb_image.h , click on RAW, rightclick, and click on save page. \
		Make sure to read the license before downloading) 

clean:
	rm convert
